### ISSUE TITLE
Incorrect initial score

### ISSUE THREAD

**Issue by petrych** [petrych/othello-cleancode#5]
![incorrect-initial-score](https://user-images.githubusercontent.com/32059360/33210228-a8748232-d119-11e7-85e8-793497167ca6.png)
Preconditions:
1. Start a new game by clicking the button "Start a human vs human game".
2. A new game is started, a user sees a board with 4 initial coins. 

Actual result:
The score is 3 for each user. See the screenshot attached.

Expected result
The score is 2 for each user.

**Comment by fyze89** [comment]
Actually, it shows 3 even if the board is empty. Just tested it.

**Comment by DizdarArmin** [comment]
This is working. Closing the issue.
